#! /bin/bash

ZEROS=0000000000000000000000000000000000000000

D=$(cd $(dirname "$0") && pwd)
MULTIMAIL="$D/post-receive-multimail/git_multimail.py"
TESTREPO=$(cd "$D"/.. && pwd)/email-test.git

cd $TESTREPO

test-email() {
    REFNAME="$1"
    OLDREV="$2"
    NEWREV="$3"
    echo "$OLDREV" "$NEWREV" "$REFNAME" | "$MULTIMAIL" --stdout
}

test-create() {
    REFNAME="$1"
    NEWREV=$(git rev-parse "$REFNAME")
    test-email "$REFNAME" "$ZEROS" "$NEWREV"
}

test-update() {
    REFNAME="$1"
    OLDREV=$(git rev-parse "$2")
    NEWREV=$(git rev-parse "$REFNAME")
    test-email "$REFNAME" "$OLDREV" "$NEWREV"
}

test-delete() {
    REFNAME="$1"
    OLDREV=$(git rev-parse "$REFNAME")
    git update-ref -d "$REFNAME" "$OLDREV" &&
    test-email "$REFNAME" "$OLDREV" "$ZEROS"
    RETCODE=$?
    git update-ref "$REFNAME" "$OLDREV" ||
        echo 1>&2 "Error replacing reference $REFNAME to $OLDREV"
    return $RETCODE
}

test-rewind() {
    REFNAME="$1"
    OLDREV=$(git rev-parse "$REFNAME")
    NEWREV=$(git rev-parse "$2")
    git update-ref "$REFNAME" "$NEWREV" "$OLDREV" &&
    test-email "$REFNAME" "$OLDREV" "$NEWREV"
    RETCODE=$?
    git update-ref "$REFNAME" "$OLDREV" ||
        echo 1>&2 "Error replacing reference $REFNAME to $OLDREV"
    return $RETCODE
}

test-create refs/heads/master
test-update refs/heads/master refs/heads/master^^
test-update refs/heads/master refs/heads/feature
test-delete refs/heads/master
test-rewind refs/heads/master refs/heads/master^^
test-rewind refs/heads/master refs/heads/feature
test-rewind refs/heads/master refs/heads/master^

test-update refs/heads/release refs/heads/release^^^^
test-rewind refs/heads/release refs/heads/release^^

test-create refs/heads/feature
test-update refs/heads/feature refs/heads/feature^^^
test-rewind refs/heads/feature refs/heads/feature^^^
test-delete refs/heads/feature

test-create refs/tags/tag
test-update refs/tags/tag refs/heads/master
test-delete refs/tags/tag

test-create refs/tags/tag-annotated
test-update refs/tags/tag-annotated refs/heads/master
test-delete refs/tags/tag-annotated

test-create refs/tags/tag-annotated-new-content
test-update refs/tags/tag-annotated-new-content refs/heads/master
test-delete refs/tags/tag-annotated-new-content

test-create refs/tags/tree-tag
test-update refs/tags/tree-tag refs/heads/master
test-delete refs/tags/tree-tag

test-create refs/tags/recursive-tag
test-update refs/tags/recursive-tag refs/heads/master
test-delete refs/tags/recursive-tag

#test-create refs/remotes/remote
#test-update refs/remotes/remote refs/heads/master
#test-delete refs/remotes/remote

#test-create refs/foo/bar
#test-update refs/foo/bar refs/heads/master
#test-delete refs/foo/bar

