#! /bin/sh

cd "${0%/*}" || exit 1
. ./helper-functions.sh || exit 1

tmp=$(mktemp -d || echo /tmp/test.$$)
mkdir -p "$tmp"

cleanup () {
	rm -fr "$tmp"
}

# In shallow clones, we may not have all revisions ...
negative_rev=$(git rev-parse 03f63a7422abfee45f2abc7af15affa48ffca666^0 2>/dev/null)
if test -n "$negative_rev"
then
	negative_rev="^$negative_rev"
fi

if ! git log --no-merges --invert-grep --grep '^Signed-off-by: ' \
    HEAD $negative_rev >"$tmp"/log-output.txt
then
	# Probably we're using a pre-2.4 version of Git that does not
	# have --invert-grep.
	git rev-list --no-merges --grep '^Signed-off-by: ' HEAD $negative_rev \
	    >"$tmp"/signed-commits.txt
	git rev-list --no-merges HEAD $negative_rev \
	    >"$tmp"/all-commits.txt
	grep -Fvf "$tmp"/signed-commits.txt "$tmp"/all-commits.txt \
	    >"$tmp"/unsigned-commits.txt
	if test -s "$tmp"/unsigned-commits.txt
	then
		git log --stdin --no-walk \
		    <"$tmp"/unsigned-commits.txt \
		    >"$tmp"/log-output.txt
	fi
fi

if test -s "$tmp"/log-output.txt
then
	cat "$tmp"/log-output.txt
	log
	fatal "Some commits lack sign-off, see above."
fi

cleanup
