#! /bin/sh

# Fake replacement for sendmail, for testing purposes.

echo "######################################################################"
printf '%s\n' "/usr/sbin/sendmail $* <<EOF"
cat
echo "EOF"
echo "######################################################################"

