#! /bin/sh

# Fake replacement for sendmail, for testing purposes.

echo "######################################################################"
echo "/usr/sbin/sendmail -t $@ <<EOF"
cat
echo "EOF"
echo "######################################################################"

