#! /bin/sh

# Filter out strings that vary uninterestingly from one test run to
# the next.

sed \
    -e 's/^\(In-Reply-To\|Message-ID\|References\): <.*>$/\1: <...>/' \
    -e 's/^\(Date\): [^ ].*$/\1: .../' \
    -e "s/^\(X-Git-Host\): `hostname --fqdn`\$/\1: fqdn.example.org/" \
    -e "s/^\(X-Git-Multimail-Version\): $MULTIMAIL_VERSION_QUOTED/\1: .../"

