#!/bin/sh

d=$(dirname "$0")

retcode=0
errors=
record_error () {
    errors="$errors $1"
    retcode=1
}

printf '%s' 'Python version: '
python --version
printf '%s' 'PEP8 version: '
pep8 --version
printf '%s' 'Git version: '
git --version
printf '%s' 'rstcheck version: '
rstcheck --version

echo

if ! rstcheck $d/../README.rst 2>&1 | tee $d/rstcheck.out || 
       test -s $d/rstcheck.out
then
    record_error RST
else
    echo "No RST error in README.rst: PASS"
fi

# W503: line break before binary operator => could eventually be
# removed, but at a moment where there are less pending PRs.
if ! pep8 $d/../git-multimail/git_multimail.py --ignore=W503
then
    record_error PEP8
else
    echo "No new PEP8 error found: PASS"
fi

if ! "$d/test-email-content"
then
    record_error test-email-content
fi

if ! "$d/test-env"
then
    record_error test-env
fi

if [ -n "$errors" ]
then
    echo "Errors found in:$errors"
fi

exit $retcode
