#!/bin/sh

d=$(dirname "$0")

echo "Comparing generated emails to $d/multimail.expect ..."

"$d/generate-test-emails" 2>&1 | "$d/filter-noise" >/tmp/multimail.actual
git diff -u "$d/multimail.expect" /tmp/multimail.actual
if test $? = 0
then
    echo "PASS"
else
    echo "
===========================================================================
FAILURE!
Please investigate the discrepancies shown above.
If you are sure that your version is correct, then please

    cp /tmp/multimail.actual $d/multimail.expect

and commit." >&2
    exit 1
fi
